export const TEST_ENTRYPOINT = 'scripts/test-suite.mjs';

export const ROOT_TEST_SCRIPT = `node --test ${TEST_ENTRYPOINT}`;

export const NODE_TEST_FILES = Object.freeze([
  'scripts/deploy-discipline.test.mjs',
  'scripts/deploy-script.test.mjs',
  'scripts/env-example-parity.test.mjs',
  'scripts/package-scripts.test.mjs',
  'scripts/project-structure.test.mjs',
  'scripts/start-all-supervisor.test.mjs',
  'tools/mcy-card-upload/upload-core.test.mjs',
  'apps/fufu-tool-site/ui_heroui_architecture.test.mjs',
  'apps/fufu-tool-site/ui_site_navigation_core.test.mjs',
  'apps/fufu-tool-site/web/status/api.test.mjs',
  'apps/fufu-tool-site/web/status/app_controller.test.mjs',
  'apps/fufu-tool-site/web/status/app_data.test.mjs',
  'apps/fufu-tool-site/web/status/app_event_keys.test.mjs',
  'apps/fufu-tool-site/web/status/app_events.test.mjs',
  'apps/fufu-tool-site/web/status/app_shell.test.mjs',
  'apps/fufu-tool-site/web/status/app_state.test.mjs',
  'apps/fufu-tool-site/web/status/app_token_group_events.test.mjs',
  'apps/fufu-tool-site/web/status/combine_card_units.test.mjs',
  'apps/fufu-tool-site/web/status/combine_token_sections.test.mjs',
  'apps/fufu-tool-site/web/status/combine_trace_results.test.mjs',
  'apps/fufu-tool-site/web/status/connectivity_probe.test.mjs',
  'apps/fufu-tool-site/web/status/connectivity_result_view.test.mjs',
  'apps/fufu-tool-site/web/status/connectivity_runner.test.mjs',
  'apps/fufu-tool-site/web/status/connectivity_states.test.mjs',
  'apps/fufu-tool-site/web/status/connectivity.test.mjs',
  'apps/fufu-tool-site/web/status/css.test.mjs',
  'apps/fufu-tool-site/web/status/dom.test.mjs',
  'apps/fufu-tool-site/web/status/model_selectors.test.mjs',
  'apps/fufu-tool-site/web/status/model_test_runner.test.mjs',
  'apps/fufu-tool-site/web/status/render_components.test.mjs',
  'apps/fufu-tool-site/web/status/render_connectivity.test.mjs',
  'apps/fufu-tool-site/web/status/render_model_scope.test.mjs',
  'apps/fufu-tool-site/web/status/render_model_table.test.mjs',
  'apps/fufu-tool-site/web/status/render_models.test.mjs',
  'apps/fufu-tool-site/web/status/render_tabs.test.mjs',
  'apps/fufu-tool-site/web/status/ui_motion.test.mjs',
  'apps/fufu-tool-site/web/status/utils.test.mjs',
  'apps/y2k-nav/admin-entry.test.mjs',
  'apps/y2k-nav/docker_assets.test.mjs',
  'apps/y2k-nav/latency.test.mjs',
  'apps/y2k-nav/theme.test.mjs',
  'apps/y2k-nav/ui_tokens.test.mjs',
  'apps/fufu-act/public/activity-api.test.mjs',
  'apps/fufu-act/public/activity-render.test.mjs',
  'apps/fufu-act/public/dragonboat-hook.test.mjs',
  'apps/fufu-act/public/index-html.test.mjs',
  'apps/fufu-act/public/scratch-card.test.mjs'
]);
