export const TEST_ENTRYPOINT = 'scripts/test-suite.mjs';

export const ROOT_TEST_SCRIPT = `node --test ${TEST_ENTRYPOINT}`;

export const NODE_TEST_FILES = Object.freeze([
  'scripts/deploy-discipline.test.mjs',
  'scripts/deploy-script.test.mjs',
  'scripts/env-example-parity.test.mjs',
  'scripts/package-scripts.test.mjs',
  'scripts/project-structure.test.mjs',
  'scripts/start-all-supervisor.test.mjs',
  'apps/mcy-card-upload/upload-core.test.mjs',
  'apps/fufu-tool-site/ui_heroui_architecture.test.mjs',
  'apps/fufu-tool-site/ui_site_navigation_core.test.mjs',
  'apps/fufu-tool-site/frontend/api.test.mjs',
  'apps/fufu-tool-site/frontend/app_controller.test.mjs',
  'apps/fufu-tool-site/frontend/app_data.test.mjs',
  'apps/fufu-tool-site/frontend/app_event_keys.test.mjs',
  'apps/fufu-tool-site/frontend/app_events.test.mjs',
  'apps/fufu-tool-site/frontend/app_shell.test.mjs',
  'apps/fufu-tool-site/frontend/app_state.test.mjs',
  'apps/fufu-tool-site/frontend/app_token_group_events.test.mjs',
  'apps/fufu-tool-site/frontend/combine_card_units.test.mjs',
  'apps/fufu-tool-site/frontend/combine_token_sections.test.mjs',
  'apps/fufu-tool-site/frontend/combine_trace_results.test.mjs',
  'apps/fufu-tool-site/frontend/connectivity_probe.test.mjs',
  'apps/fufu-tool-site/frontend/connectivity_result_view.test.mjs',
  'apps/fufu-tool-site/frontend/connectivity_runner.test.mjs',
  'apps/fufu-tool-site/frontend/connectivity_states.test.mjs',
  'apps/fufu-tool-site/frontend/connectivity.test.mjs',
  'apps/fufu-tool-site/frontend/css.test.mjs',
  'apps/fufu-tool-site/frontend/dom.test.mjs',
  'apps/fufu-tool-site/frontend/model_selectors.test.mjs',
  'apps/fufu-tool-site/frontend/model_test_runner.test.mjs',
  'apps/fufu-tool-site/frontend/render_components.test.mjs',
  'apps/fufu-tool-site/frontend/render_connectivity.test.mjs',
  'apps/fufu-tool-site/frontend/render_model_scope.test.mjs',
  'apps/fufu-tool-site/frontend/render_model_table.test.mjs',
  'apps/fufu-tool-site/frontend/render_models.test.mjs',
  'apps/fufu-tool-site/frontend/render_tabs.test.mjs',
  'apps/fufu-tool-site/frontend/ui_motion.test.mjs',
  'apps/fufu-tool-site/frontend/utils.test.mjs',
  'apps/y2k-nav/admin-entry.test.mjs',
  'apps/y2k-nav/docker_assets.test.mjs',
  'apps/y2k-nav/latency.test.mjs',
  'apps/y2k-nav/theme.test.mjs',
  'apps/y2k-nav/ui_tokens.test.mjs',
  'apps/fufu-act/public/activity-api.test.mjs',
  'apps/fufu-act/public/activity-render.test.mjs',
  'apps/fufu-act/public/dragonboat-hook.test.mjs',
  'apps/fufu-act/public/index-html.test.mjs',
  'apps/fufu-act/public/scratch-card.test.mjs'
]);
